"""remove_entry_status

Revision ID: e70ae010566f
Revises: e9d8b6cc5488
Create Date: 2025-06-02 23:51:17.704409

"""
# isort: skip_file
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70ae010566f'
down_revision: Union[str, None] = 'e9d8b6cc5488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rss_entry_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rss_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SMALLINT(), nullable=False))
        batch_op.create_index(batch_op.f('idx_rss_entry_status'), ['status'], unique=False)

    # ### end Alembic commands ###
