"""add_entry_summary

Revision ID: 764248e1a5f7
Revises: e70ae010566f
Create Date: 2025-06-03 01:53:09.184125

"""

# isort: skip_file
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "764248e1a5f7"
down_revision: Union[str, None] = "e70ae010566f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
