"""add_entry_score

Revision ID: 47ba3cdb7085
Revises: f582b4ea3cae
Create Date: 2025-05-27 16:47:30.381174

"""

# isort: skip_file
from typing import Union
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "47ba3cdb7085"
down_revision: Union[str, None] = "f582b4ea3cae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
