"""rename_feed_tags_to_entries_tags

Revision ID: f582b4ea3cae
Revises: 3658edde1232
Create Date: 2025-05-27 16:29:01.940627

"""

# isort: skip_file
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f582b4ea3cae"
down_revision: Union[str, None] = "3658edde1232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entries_tags", schema=None) as batch_op:
        batch_op.create_index(
            "idx_entries_tags_entry_id", ["entry_id"], unique=False
        )
        batch_op.create_index(
            "idx_entries_tags_tag_id", ["tag_id"], unique=False
        )

    op.drop_table("content_tags")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("level", sa.SmallInteger(), nullable=False)
        )
        batch_op.create_index("idx_tags_level", ["level"], unique=False)
        batch_op.create_index("idx_tags_parent_id", ["parent_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_tags_name_parent", ["name", "parent_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_constraint("uq_tags_name_parent", type_="unique")
        batch_op.drop_index("idx_tags_parent_id")
        batch_op.drop_index("idx_tags_level")
        batch_op.drop_column("level")
        batch_op.drop_column("parent_id")

    op.create_table(
        "content_tags",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("feed_id", sa.INTEGER(), nullable=False),
        sa.Column("tag_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entries_tags", schema=None) as batch_op:
        batch_op.drop_index("idx_entries_tags_tag_id")
        batch_op.drop_index("idx_entries_tags_entry_id")

    op.drop_table("entries_tags")
    # ### end Alembic commands ###
