"""add_entry_summary

Revision ID: 6858dee2ac72
Revises: e70ae010566f
Create Date: 2025-06-03 15:06:32.119502

"""

# isort: skip_file
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6858dee2ac72"
down_revision: Union[str, None] = "e70ae010566f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("ai_summary", sa.String(length=255), nullable=False),
        sa.Column("created_gmt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", name="unique_entry_summary_entry_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entry_summary")
    # ### end Alembic commands ###
