"""rename_entry_category

Revision ID: e9d8b6cc5488
Revises: 23e4b8ab0758
Create Date: 2025-06-02 23:43:32.306724

"""

# isort: skip_file
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9d8b6cc5488"
down_revision: Union[str, None] = "23e4b8ab0758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entry_category", schema=None) as batch_op:
        batch_op.create_index(
            "idx_entry_category_category", ["category"], unique=False
        )
        batch_op.create_index(
            "idx_entry_category_entry_id", ["entry_id"], unique=False
        )

    with op.batch_alter_table("entries_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_entries_categories_category"))
        batch_op.drop_index(batch_op.f("idx_entries_categories_entry_id"))

    op.drop_table("entries_categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries_categories",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("entry_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("category", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entries_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_entries_categories_entry_id"),
            ["entry_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_entries_categories_category"),
            ["category"],
            unique=False,
        )

    with op.batch_alter_table("entry_category", schema=None) as batch_op:
        batch_op.drop_index("idx_entry_category_entry_id")
        batch_op.drop_index("idx_entry_category_category")

    op.drop_table("entry_category")
    # ### end Alembic commands ###
