"""rss_feed_add_unique_index

Revision ID: 3658edde1232
Revises: 4270c6fdeddb
Create Date: 2025-05-26 18:08:46.076642

"""

# isort: skip_file
from typing import Union
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3658edde1232"
down_revision: Union[str, None] = "4270c6fdeddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support adding constraints directly, so we recreate the table
    with op.batch_alter_table("rss_feed", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_rss_feed_link", ["link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rss_feed", schema=None) as batch_op:
        batch_op.drop_constraint("uix_rss_feed_link", type_="unique")
    # ### end Alembic commands ###
