"""rssFeeds to rss feed and add rss entry

Revision ID: fb27a9631c8b
Revises: 8f6f8fbc6e2b
Create Date: 2025-05-25 11:45:53.522306

"""
# This file is auto-generated by Alembic. DO NOT EDIT! 
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb27a9631c8b'
down_revision: Union[str, None] = '8f6f8fbc6e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_gmt', sa.DateTime(), nullable=False),
    sa.Column('modified_gmt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link', name='unique_source_type_source_url')
    )
    op.create_index('idx_tb_rss_feeds_published_at', 'rss_entry', ['published_at'], unique=False)
    op.create_index('idx_tb_rss_feeds_status', 'rss_entry', ['status'], unique=False)
    op.create_table('rss_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_tb_rss_feeds_published_at'), table_name='rss_feeds')
    op.drop_index(op.f('idx_tb_rss_feeds_status'), table_name='rss_feeds')
    op.drop_table('rss_feeds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feeds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_url', name=op.f('unique_source_type_source_url'))
    )
    op.create_index(op.f('idx_tb_rss_feeds_status'), 'rss_feeds', ['status'], unique=False)
    op.create_index(op.f('idx_tb_rss_feeds_published_at'), 'rss_feeds', ['published_at'], unique=False)
    op.drop_table('rss_feed')
    op.drop_index('idx_tb_rss_feeds_status', table_name='rss_entry')
    op.drop_index('idx_tb_rss_feeds_published_at', table_name='rss_entry')
    op.drop_table('rss_entry')
    # ### end Alembic commands ###
