name: Migration Tests

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/migrate/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'alembic/**'

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.2"

    - name: Install dependencies
      run: |
        uv sync

    - name: Test migrations from empty database
      run: |
        alembic upgrade head

    - name: Test migrations from current version to next version
      run: |
        rm -f app.db
        git checkout main
        alembic upgrade head
        git checkout HEAD~1
        alembic upgrade head
