name: Migration Tests

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/migrate/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/migrate/**'

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - name: "Empty database"
            commands: |
              uv run alembic upgrade head
          - name: "Version upgrade"
            commands: |
              git fetch origin main
              git checkout origin/main
              uv run alembic upgrade head
              git checkout HEAD~1
              uv run alembic upgrade head
    
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.2"

    - name: Install dependencies
      run: |
        uv sync

    - name: Run migration tests
      run: ${{ matrix.test-case.commands }}
