name: Build Test

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.2"

    - name: Install dependencies
      run: |
        uv sync

    - name: Run build 
      run: |
        uv build